coverage:
  precision: 1
  round: down
  range: "80...100"
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 60%
        threshold: 5%

comment: false

github_checks:
  annotations: false
