package cli

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/wnstify/wdm/pkg/engine"
	"github.com/wnstify/wdm/pkg/types"
)

// confirmationKindDatabaseRisk is the [types.Confirmation.Kind] the engine
// emits for the PRD §20 database-risk update warning. It is the one
// consequence class --yes must NOT satisfy: the confirmation rulesreserves
// that gate for an explicit --accept-database-risk flag, and the confirmation rules
// fixes its no-TTY default as "reject rather than auto-accept".
// [types.Confirmation] carries no acceptance-token field, so the gate keys on
// this stable Kind string. Install never produces this Kind, but the
// [types.Confirmer] is shared across every lifecycle command, so the guard
// lives in the shared CLI confirmer where no future caller can wire --yes onto
// a database-risk path.
const confirmationKindDatabaseRisk = "update_database_risk"

// acceptDatabaseRiskFlag is the explicit opt-in a user passes on `apps update`
// to authorize a database-risk update non-interactively
// #14/#19). The confirmer names it in the refusal guidance, so the literal
// lives in one place.
const acceptDatabaseRiskFlag = "--accept-database-risk"

// newAppsInstallCmd builds the `apps install <app-id>` leaf (PRD §17, §32;
// injected factory and renders [types.InstallResult] in one of two forms based
// on the root's --json persistent flag:
//   - Plain mode: the PRD §16 install-finish screen on stdout — the single
//     local target URL, every bound localhost port, Pangolin guidance, and
//     first-run notes. Progress events stream to stderr (golang-cli: output to
//     stdout, diagnostics to stderr).
//   - JSON mode: the full result wrapped in the wdm.v1 envelope on stdout, and
//     nothing else (PRD §32). Progress is suppressed so the envelope is the
//     only thing a parser sees.
//
// Flags:
//   - --domain: the public domain for the app. Left optional rather than
//     cobra-required so the engine owns validation — it rejects an empty
//     required domain with [types.ErrCodeUsageValidation] and requires a
//     domain only for apps whose catalog placeholder is required.
//   - --stack-path: overrides the default ~/docker/<app> stack path.
//   - --set KEY=VALUE: supplies a catalog placeholder value (repeatable). It
//     is the only way to provide required non-secret placeholders the engine
//     cannot derive — for example Jellyfin's MEDIA_PATH / MOVIES_PATH /
//     SHOWS_PATH host paths, without which the app is uninstallable from the
//     CLI. The pair is parsed CLI-side and mapped verbatim onto
//     [types.InstallRequest.PlaceholderValues]; the engine owns all key, type,
//     and value validation. See [parseSetFlags].
//   - --yes: accepts SAFE confirmations only. It
//     never accepts the database-risk warning — see [cliConfirmer.Confirm].
//
// The engine factory is invoked inside RunE, and only there, so
// `wdm apps install --help` never reaches [engine.New] (PRD §14 self-update
// smoke-check invariant, mirrored from `apps list`).
func newAppsInstallCmd(newEngine func() (engine.Engine, error)) *cobra.Command {
	var (
		domain    string
		stackPath string
		setValues []string
		assumeYes bool
	)

	cmd := &cobra.Command{
		Use:   "install <app-id>",
		Short: "Install and start a curated Docker Compose stack",
		Long: `Install installs a curated app: it renders the stack files,
generates secrets, validates the Docker Compose configuration,
confirms before deployment, and starts the stack as the current user.

Use --set KEY=VALUE (repeatable) to supply catalog placeholder values
the engine cannot derive on its own — for example the host media paths
Jellyfin requires (--set MEDIA_PATH=/srv/media). Values may contain '='
(the pair is split at the first '='); an empty value is allowed and the
engine decides what it means for the placeholder. Unknown keys, missing
required placeholders, and invalid values are rejected by the engine.

Secret placeholders are generated by wdm with a cryptographic source and
cannot be set with --set; any --set value for a secret placeholder has no
effect. The public domain is supplied with --domain, which fills the app's
domain placeholder whatever its catalog name. A --set for that placeholder
by its exact catalog name takes precedence over --domain when both are
given.

The deployment confirmation can be accepted non-interactively with
--yes. --yes accepts only safe confirmations; it never accepts the
database-risk update warning.`,
		Args:          cobra.ExactArgs(1),
		SilenceUsage:  true,
		SilenceErrors: true,
		RunE: func(cmd *cobra.Command, args []string) error {
			useJSON, err := cmd.Flags().GetBool("json")
			if err != nil {
				return fmt.Errorf("apps install: reading --json: %w", err)
			}

			// Parse --set before constructing the engine: a malformed pair is
			// a usage error, and refusing it here keeps the engine and
			// runtime.lock untouched on a bad invocation.
			placeholders, err := parseSetFlags(setValues)
			if err != nil {
				return err
			}

			eng, err := newEngine()
			if err != nil {
				return err
			}
			defer eng.Close() //nolint:errcheck // best-effort cleanup; engine.Close releases flock handles and logs internally

			req := types.InstallRequest{
				AppID:             args[0],
				Domain:            domain,
				StackPath:         stackPath,
				PlaceholderValues: placeholders,
			}

			// Install never produces a database-risk confirmation, so
			// acceptDBRisk is wired false; that flag lives only on `apps update`.
			confirmer, onProgress := stateChangeIO(cmd, assumeYes, false, useJSON)

			result, err := eng.Install(cmd.Context(), req, onProgress, confirmer)
			if err != nil {
				return err
			}

			return emitResult(cmd, useJSON, result, writeInstallFinish)
		},
	}

	cmd.Flags().StringVar(&domain, "domain", "", "public domain for the app (for example app.example.com)")
	cmd.Flags().StringVar(&stackPath, "stack-path", "", "override the default ~/docker/<app> stack path")
	cmd.Flags().StringArrayVar(&setValues, "set", nil, "set a catalog placeholder as KEY=VALUE (repeatable); secret placeholders are generated and cannot be set")
	cmd.Flags().BoolVar(&assumeYes, "yes", false, "accept safe confirmations without prompting (never the database-risk warning)")

	return cmd
}

// parseSetFlags turns the repeatable --set KEY=VALUE pairs into the
// placeholder map for [types.InstallRequest.PlaceholderValues]. It is
// deliberately thin: the engine owns every semantic check. This function
// refuses only the malformed shapes the engine cannot report — a pair with no
// '=' and a pair with an empty KEY — plus a duplicate KEY, which is almost
// always a typo. All three are plain (non-typed) errors, so cmd/wdm's
// exitCodeFor default arm maps them to exit 2 (usage).
// Splitting at the FIRST '=' lets a VALUE contain '=' (a base64 or
// query-string value). An empty VALUE is legal and passed through unchanged;
// the engine decides what it means for the placeholder's type.
// No --set flags returns a nil map, identical to the pre-flag behavior.
func parseSetFlags(pairs []string) (map[string]string, error) {
	if len(pairs) == 0 {
		return nil, nil
	}

	values := make(map[string]string, len(pairs))
	for _, pair := range pairs {
		key, value, found := strings.Cut(pair, "=")
		if !found {
			return nil, fmt.Errorf("apps install: invalid --set %q: expected KEY=VALUE", pair)
		}
		if key == "" {
			return nil, fmt.Errorf("apps install: invalid --set %q: empty placeholder key", pair)
		}
		if _, dup := values[key]; dup {
			return nil, fmt.Errorf("apps install: duplicate --set key %q", key)
		}
		values[key] = value
	}
	return values, nil
}

// stderrProgress returns a [types.ProgressFn] that writes one line per
// progress event to w (the command's stderr). Write errors are dropped:
// progress is advisory, and a failed stderr write must not abort an otherwise
// succeeding install — there is nothing actionable to do with a broken stderr
// from inside a progress callback.
func stderrProgress(w io.Writer) types.ProgressFn {
	return func(_ string, _ float64, msg string) {
		fmt.Fprintf(w, "... %s\n", msg) //nolint:errcheck // advisory progress; a broken stderr is not actionable here
	}
}

// writeInstallFinish renders the PRD §16 install-finish screen for a
// successful install to w (stdout): the single local target URL, every bound
// localhost port, the Pangolin recommendation, and any first-run notes.
// while the JSON envelope carries the full port list; this screen also lists
// the bound ports beneath the URL so a human sees every binding without --json.
func writeInstallFinish(w io.Writer, result *types.InstallResult) error {
	var b strings.Builder

	fmt.Fprintf(&b, "%s is installed at %s\n", result.AppID, result.StackPath)

	guidance := result.PostInstallGuidance
	if guidance != nil && guidance.LocalTargetURL != "" {
		fmt.Fprintf(&b, "\nRunning locally at:\n  %s\n", guidance.LocalTargetURL)
	}

	if len(result.LocalPorts) > 0 {
		b.WriteString("\nBound ports:\n")
		for _, p := range result.LocalPorts {
			fmt.Fprintf(&b, "  %s:%d -> %s\n", p.HostIP, p.HostPort, p.Service)
		}
	}

	if guidance != nil && guidance.Pangolin != nil {
		writePangolinGuidance(&b, guidance.Pangolin)
	}

	if guidance != nil && len(guidance.FirstRunNotes) > 0 {
		b.WriteString("\nFirst run:\n")
		for _, note := range guidance.FirstRunNotes {
			fmt.Fprintf(&b, "  %s\n", note)
		}
	}

	if guidance != nil && len(guidance.GeneratedCredentials) > 0 {
		writeGeneratedCredentials(&b, guidance.GeneratedCredentials)
	}

	if _, err := io.WriteString(w, b.String()); err != nil {
		return fmt.Errorf("apps install: writing finish screen: %w", err)
	}
	return nil
}

// writePangolinGuidance appends the reverse-proxy recommendation block
// (PRD §16) to b. Pangolin is the recommended path; the block names the
// target URL to proxy, the suggested subdomain, and any operator notes.
func writePangolinGuidance(b *strings.Builder, p *types.PangolinGuidance) {
	b.WriteString("\nRecommended: expose with Pangolin\n")
	if p.RecommendedSubdomain != "" {
		fmt.Fprintf(b, "  subdomain: %s\n", p.RecommendedSubdomain)
	}
	if p.TargetURL != "" {
		fmt.Fprintf(b, "  point it to: %s\n", p.TargetURL)
	}
	for _, note := range p.Notes {
		fmt.Fprintf(b, "  %s\n", note)
	}
}

// writeGeneratedCredentials appends the one-time credential block to b.
// These plaintexts are shown exactly once: wdm persists only a one-way
// hash, so the operator must record each value now. The block is
// human-only — the --json path omits it entirely (PRD §24, enforced by the
// json:"-" tag on [types.PostInstallGuidance.GeneratedCredentials]).
func writeGeneratedCredentials(b *strings.Builder, creds []types.GeneratedCredential) {
	b.WriteString("\n========================================\n")
	b.WriteString("SAVE THIS NOW — shown once, cannot be recovered\n")
	b.WriteString("========================================\n")
	for _, cred := range creds {
		if cred.Label != "" {
			fmt.Fprintf(b, "  %s:\n", cred.Label)
		}
		fmt.Fprintf(b, "    %s\n", cred.Value)
		if cred.Note != "" {
			fmt.Fprintf(b, "    %s\n", cred.Note)
		}
	}
}

// cliConfirmer is the [types.Confirmer] used by the lifecycle commands.
// It authorizes a [types.Confirmation] either non-interactively (--yes
// for safe confirmations, --accept-database-risk for the one database-risk
// warning) or by prompting on a TTY, and rejects fail-closed when it can
// neither prompt nor auto-accept.
type cliConfirmer struct {
	out          io.Writer // finish/result stream (stdout); unused by the prompt itself
	err          io.Writer // prompt + diagnostics stream (stderr)
	in           io.Reader // answer source (stdin)
	yes          bool      // --yes: accept safe confirmations without prompting
	acceptDBRisk bool      // --accept-database-risk: accept the database-risk warning
	isTTY        bool      // whether stdin is an interactive terminal
}

// newCLIConfirmer builds a [cliConfirmer]. isTTY is probed once from os.Stdin
// so the gating decision is stable for the command's lifetime, independent of
// which reader is injected for the answer source (tests inject a buffer for in
// without making stdin a terminal).
// acceptDBRisk is the explicit --accept-database-risk opt-in. Only
// `apps update` wires it true; the others pass false because they never
// produce a database-risk confirmation, and false keeps that path fail-closed.
func newCLIConfirmer(out, errOut io.Writer, in io.Reader, assumeYes, acceptDBRisk bool) *cliConfirmer {
	return &cliConfirmer{
		out:          out,
		err:          errOut,
		in:           in,
		yes:          assumeYes,
		acceptDBRisk: acceptDBRisk,
		isTTY:        stdinIsTTY(),
	}
}

// Confirm implements [types.Confirmer]. The gating matrix is:
//
//	                                   | TTY | no TTY
//	-----------------------------------+------------+------------------
//	safe + --yes | accept | accept
//	safe + no --yes | prompt y/N | reject (canceled)
//	database-risk + --accept-db-risk | accept | accept
//	database-risk + no flag | refuse* | refuse*
//
// *refuse: the engine's verbatim PRD §20 warning (confirmation.Message) is
// printed to stderr and the operation is declined with guidance naming
// --accept-database-risk.
// The database-risk row is FLAG-ONLY: a TTY "y" never satisfies it and --yes
// never satisfies it. the confirmation rulesand #19 phrase database-risk
// acceptance as the flag, and reserves the interactive flow for
// "update_deploy" or "install_deploy") keeps the interactive posture: accepted
// by --yes, otherwise prompted on a TTY and declined without one.
// Reject/refuse return (false, nil); the engine maps that to
// [types.ErrCodeUserCanceled]. The database-risk refusal
// prints the warning plus flag guidance first so the user knows how to
// authorize. A context cancellation surfaces as a non-nil error so the engine
// can abort promptly.
func (c *cliConfirmer) Confirm(ctx context.Context, confirmation types.Confirmation) (bool, error) {
	if err := ctx.Err(); err != nil {
		return false, err
	}

	if confirmation.Kind == confirmationKindDatabaseRisk {
		return c.confirmDatabaseRisk(confirmation), nil
	}

	if c.yes {
		return true, nil
	}

	if !c.isTTY {
		// No terminal to prompt on and no --yes: refuse rather than block or
		// silently proceed.
		return false, nil
	}

	return c.prompt(ctx, confirmation)
}

// confirmDatabaseRisk authorizes or refuses the PRD §20 database-risk warning.
// Authorization is FLAG-ONLY: --accept-database-risk accepts, its absence
// refuses regardless of TTY. The verbatim
// warning is printed to stderr on both paths — on refusal so the decline is
// never silent (the engine maps the returned false to
// [types.ErrCodeUserCanceled]), and on acceptance so a non-interactive
// operator sees what was authorized before any backup, rewrite, pull, or
// recreate runs.
func (c *cliConfirmer) confirmDatabaseRisk(confirmation types.Confirmation) bool {
	fmt.Fprintf(c.err, "\n%s\n", confirmation.Title) //nolint:errcheck // advisory diagnostics; the decision below is flag-driven
	fmt.Fprintf(c.err, "%s\n", confirmation.Message) //nolint:errcheck // see above
	if c.acceptDBRisk {
		fmt.Fprintf(c.err, "Accepted via %s.\n", acceptDatabaseRiskFlag) //nolint:errcheck // see above
		return true
	}
	fmt.Fprintf(c.err, "Refusing: pass %s to authorize this database-risk update.\n", acceptDatabaseRiskFlag) //nolint:errcheck // see above
	return false
}

// prompt renders the confirmation banner to stderr and reads a single
// y/N answer from the configured reader. The default is No: an empty
// line, EOF, or any non-affirmative answer declines. Only "y"/"yes"
// (case-insensitive, whitespace-trimmed) accepts.
func (c *cliConfirmer) prompt(ctx context.Context, confirmation types.Confirmation) (bool, error) {
	fmt.Fprintf(c.err, "\n%s\n", confirmation.Title) //nolint:errcheck // prompt is advisory; the read below drives the decision
	fmt.Fprintf(c.err, "%s\n", confirmation.Message) //nolint:errcheck // see above
	fmt.Fprint(c.err, "Proceed? [y/N]: ")            //nolint:errcheck // see above

	reader := bufio.NewReader(c.in)
	line, err := reader.ReadString('\n')
	if err != nil && err != io.EOF {
		return false, fmt.Errorf("apps install: reading confirmation: %w", err)
	}

	// A context canceled while we were blocked on input must abort.
	if cerr := ctx.Err(); cerr != nil {
		return false, cerr
	}

	switch strings.ToLower(strings.TrimSpace(line)) {
	case "y", "yes":
		return true, nil
	default:
		return false, nil
	}
}

// stdinIsTTY reports whether standard input is plausibly an interactive
// terminal, using only the standard library. The char-device heuristic
// distinguishes pipes and redirected files (non-TTY) from terminals; it does
// NOT distinguish char-special non-terminals: `wdm... < /dev/null` reads as a
// char device and reaches the prompt, whose immediate EOF declines (the
// default answer is No). Every non-interactive shape still fails closed —
// pipes and redirected files reject before the prompt, /dev/null declines at
// it — through two different arms.
func stdinIsTTY() bool {
	info, err := os.Stdin.Stat()
	if err != nil {
		return false
	}
	return info.Mode()&os.ModeCharDevice != 0
}
