// Package render implements the wdm template renderer. It projects
// the catalog placeholder shape into a render-local type, validates
// placeholder sets and their resolved value maps, and renders the
// Compose, .env, and sidecar-file templates with wdm managed labels
// and bind-mount safety invariants.
// Boundary contract: internal/render is pure,
// depending only on the standard library and pkg/types. Importing any
// internal/* sibling — catalog, core, docker, security, state, logging,
// system, cli, tui — is rejected by the internal-render-pure depguard
// rule in .golangci.yml. The projection from
// internal/catalog.Placeholder to [Placeholder] happens inside
// internal/core; render never reaches into the catalog package.
package render

// Type is a placeholder's leaf type. The closed set mirrors the
// catalog/schema.json placeholder.type enum; extending it requires a coordinated
// schema bump in catalog/schema.json and a renderer change here.
type Type string

// Placeholder leaf types. The set is closed; [Type.IsValid] enforces
// membership at validation time.
const (
	// TypeString is a free-form scalar value. Render performs no
	// value validation for this leaf type.
	TypeString Type = "string"

	// TypeDomain is a DNS hostname. Domain syntax validation runs
	// in internal/core before render is called, not here.
	TypeDomain Type = "domain"

	// TypePort is a TCP/UDP port number. Port-range and
	// host-availability validation runs in internal/core before
	// render is called, not here.
	TypePort Type = "port"

	// TypeSecret is a credential generated by wdm.
	// [Placeholder.Regenerable] carries the per-secret rotation
	// policy. Render never echoes resolved
	// values to error messages, logs, or any other sink.
	TypeSecret Type = "secret"

	// TypeTimezone is an IANA timezone identifier. IANA validation
	// runs in internal/core before render is called, not here.
	TypeTimezone Type = "timezone"

	// TypePath is an absolute host filesystem path. Path-safety
	// validation (must-exist, must-be-outside-stack-dir, symlink
	// resolution) runs in internal/core before render is called,
	// not here.
	TypePath Type = "path"

	// TypeBool is a string-encoded boolean ("true" / "false") at
	// the .env layer. Parse validation runs in internal/core before
	// render is called, not here.
	TypeBool Type = "bool"
)

// IsValid reports whether t is one of the closed enum values
// declared above.
func (t Type) IsValid() bool {
	switch t {
	case TypeString, TypeDomain, TypePort, TypeSecret,
		TypeTimezone, TypePath, TypeBool:
		return true
	}
	return false
}

// Placeholder is render's local projection of the catalog placeholder
// shape. It carries only the fields render needs to validate
// placeholder sets and resolve them against a value map; catalog-side
// schema metadata (description, regex constraints, SQL-identifier
// denylist scoping, etc.) stays in internal/catalog and never crosses
// the projection boundary in internal/core.
// [Placeholder.Regenerable] mirrors
// internal/catalog.Placeholder.Regenerable: nil means "use the default"
// (true — install always regenerates); an explicit false marks the secret
// fixed-after-install, and the update path reuses the existing .env value
// via state.ReadStackEnv. Only meaningful when [Type] is
// [TypeSecret]; render does not enforce the scoping (the catalog
// schema rejects the field on non-secret placeholders before the
// projection reaches render).
type Placeholder struct {
	// Name is the placeholder identifier as it appears in templates
	// (uppercase snake, e.g. "DB_PASSWORD"). Render rejects empty
	// names via [ValidatePlaceholders]; the uppercase-snake pattern
	// is enforced upstream by catalog/schema.json.
	Name string

	// Type is the placeholder leaf type from the closed enum
	// declared above. [ValidatePlaceholders] rejects values outside
	// that set.
	Type Type

	// Required indicates whether resolution must supply a value
	// (true) or may omit it (false, falling back to [Default] at
	// render time).
	Required bool

	// Default is the optional default value. Its concrete type
	// mirrors the leaf [Type]; render carries it as any so the
	// catalog-side YAML scalar (string / number / boolean / null)
	// survives projection. Default-value type matching against [Type]
	// happens at render time, not in [ValidatePlaceholders].
	Default any

	// Regenerable is the per-secret rotation policy. A nil value
	// is distinct from an explicit false. Only meaningful on
	// [TypeSecret] placeholders.
	Regenerable *bool
}

// Input is the render-local projection of catalog data plus the
// pre-resolved placeholder value map. internal/core builds it from
// the catalog entry and the resolved-secrets/paths/timezone map
// before calling any render entry point; keeps render pure with no
// internal/catalog import. Render owns its own [Placeholder] projection.
// The field set supports env rendering, Compose rendering, label
// enforcement, and additional files so [RenderLabels] can verify
// catalog-declared mounts and render sidecar templates in memory.
type Input struct {
	// EnvTemplate is the .env.tmpl content as text. internal/core
	// reads the template file from disk and passes its content here;
	// render performs no filesystem I/O.
	EnvTemplate string

	// ComposeTemplate is the docker-compose.yml.tmpl content as text.
	// internal/core reads the template file from disk and passes its
	// content here; render performs no filesystem I/O. Compose
	// templates keep shell-style ${VAR} references for
	// env-supplied values (Compose's runtime --env-file substitution
	// per the confirmation rules); any {{.Identifier }} references
	// are substituted from [Values] at render time. Curated templates
	// should use Go-template actions only for values that must be
	// resolved before Compose runs, such as built-in UID/GID.
	ComposeTemplate string

	// Placeholders is the declared placeholder set, projected from
	// internal/catalog.App.Placeholders inside internal/core.
	// [ValidatePlaceholders] checks structural well-formedness;
	// [ValidateResolution] pairs it against [Values].
	Placeholders []Placeholder

	// Values is the pre-resolved placeholder value map, keyed by
	// [Placeholder.Name]. internal/core builds it by generating
	// secrets via internal/security.GenerateSecret, validating
	// paths/domains/ports/timezone, and propagating built-in vars
	// before the render call.
	// Render hands it to text/template Execute unmodified and never
	// echoes the values into error messages, logs, or any other sink
	Values map[string]string

	// AppID is the stable catalog slug projected from
	// internal/catalog.App.AppID (e.g. "uptime-kuma", "freshrss",
	// "jellyfin", "n8n" — the PRD §15 v1 set). It is the SAME
	// identifier wdm uses as the stack subdirectory name
	// (~/docker/<app_id>) and the Compose project suffix
	// (--project-name wdm-<app_id>) per PRD §9, §17. [RenderLabels]
	// injects it as the wdm.app=<AppID> label on every Compose service
	// so label, directory name, Compose project name, and managed-stack
	// identity share one stable token.
	// internal/core supplies the catalog entry's app_id field, NOT the
	// human-readable app.name ("Uptime Kuma", "FreshRSS") used for
	// catalog browsing and finish-screen copy: passing app.name would
	// drift the wdm.app label off the slug and break managed-check
	// identity matching.
	// Ignored by [RenderEnv].
	AppID string

	// AdditionalFiles is the render-local projection of catalog
	// additional_files entries plus their template contents.
	// internal/core reads each source file and passes the bytes as
	// [AdditionalFile.Template]; render verifies [AdditionalFile.Mount]
	// against the parsed Compose volumes and renders the template in
	// memory. Ignored by [RenderEnv].
	AdditionalFiles []AdditionalFile

	// ConfigGeneration is the render-local projection of
	// internal/catalog.App.ConfigGeneration: the template-rendered
	// config artifacts wdm generates itself (PRD §17). internal/core
	// reads each catalog template path off disk and passes its content
	// as [ConfigArtifact.Template]; render parses it against [Values],
	// verifies [ConfigArtifact.Mount] against the parsed Compose
	// volumes, and traversal-checks [ConfigArtifact.Dest] before
	// rendering. Ignored by [RenderEnv]; rendered,
	// mount-verified, and dest-traversal-checked by [RenderLabels].
	ConfigGeneration []ConfigArtifact
}

// AdditionalFile is render's local projection of a catalog sidecar
// artifact. It mirrors the downstream [RenderedFile] destination
// shape and adds the in-memory template body plus optional Compose
// mount string that [RenderLabels] verifies.
type AdditionalFile struct {
	Dest     string
	Mode     string
	Mount    string
	Template string
}

// ConfigArtifact is render's local projection of a catalog
// config_generation entry plus its template body. It is distinct from
// [AdditionalFile] per PRD §17 / Decision #75: the source is a
// template wdm renders, not a static file it copies. [Template] is the
// in-memory template CONTENT (mirroring [AdditionalFile.Template]) —
// internal/core reads the catalog template path off disk and passes
// the bytes, so render does no filesystem I/O. [Dest] is stack-relative
// and traversal-checked at render per PRD §12/§13; [Mount], when set,
// must already exist in the Compose volumes (render verifies, never
// injects).
type ConfigArtifact struct {
	Dest     string
	Mode     string
	Mount    string
	Template string
}

// RenderedStack is the in-memory result of rendering an app's
// templates. Each field is a distinct artifact
// the downstream write path (internal/state) commits to disk or that
// the install/update orchestrator consults at deploy time.
// Population is split by render entry point:
// [RenderEnv] fills [EnvBytes]; [RenderLabels] fills [ComposeBytes],
// [ServiceLabels], and [AdditionalFiles] when [Input.AdditionalFiles] is
// supplied. The .wdm.lock manifest is NOT a render artifact: core owns
// manifest construction in internal/state (render must not import it per the
// internal-render-pure depguard rule, and the manifest needs deploy-time data
// render cannot know). Each field's godoc below names the entry point that
// populates it.
// Render is pure: it produces this value in memory with no filesystem
// side effects. Only the downstream write path touches disk.
type RenderedStack struct {
	// ComposeBytes is the rendered docker-compose.yml content.
	// [RenderLabels] populates it: the template body with [Input.Values]
	// substitution applied, plus the mandatory wdm.managed="true" /
	// wdm.app=<AppID> label injection via the gopkg.in/yaml.v3 parse-
	// mutate-emit cycle. The internal/core install/update path calls
	// [RenderLabels] so the on-disk docker-compose.yml carries the labels.
	// Repeated renders of the same Input are byte-identical:
	// text/template Execute is deterministic and action-free bodies
	// are emitted contiguously, yaml.v3 iteration follows the Content
	// slice (no map iteration), and [RenderLabels] uses a fixed
	// 2-space encoder indent.
	ComposeBytes []byte

	// EnvBytes is the rendered .env content carrying literal values
	// (secrets included). The install/update path writes it to disk at
	// mode 0o600. Populated by [RenderEnv].
	EnvBytes []byte

	// AdditionalFiles is the rendered sidecar artifacts declared by
	// catalog additional_files (DB init scripts, web-server configs,
	// nested-path config files) per the confirmation rules. Populated
	// by [RenderLabels] when [Input.AdditionalFiles] is supplied; nil
	// otherwise.
	AdditionalFiles []RenderedFile

	// ConfigArtifacts is the rendered config_generation artifacts
	// declared by catalog config_generation (PRD §17). Populated by
	// [RenderLabels] when [Input.ConfigGeneration] is supplied; nil
	// otherwise. The install/update writer commits them like
	// [AdditionalFiles].
	ConfigArtifacts []RenderedFile

	// VolumeMounts lists the volume mount specs declared by the
	// rendered Compose services (e.g. "./data:/app/data" or
	// "named-volume:/var/lib/data"), sorted and deduplicated.
	// Populated by [RenderLabels] during the same YAML walk that
	// injects labels; internal/core surfaces the entries in the
	// pre-deployment confirmation payload so the user sees the volumes
	// the deployment will create. Not populated by [RenderEnv].
	VolumeMounts []string

	// ServiceLabels is the per-service label set the renderer enforces
	// on every Compose service (mandatory wdm.managed="true" and
	// wdm.app=<AppID>). The outer map
	// is keyed by Compose service name; the inner map carries label
	// key → value, including any pre-existing labels the template
	// declared alongside the injected pair. Populated by
	// [RenderLabels]; not by [RenderEnv].
	ServiceLabels map[string]map[string]string
}

// RenderedFile is one entry in [RenderedStack.AdditionalFiles]. The
// shape mirrors internal/catalog.AdditionalFile verbatim (Dest and
// Mode field names and types match the catalog form) plus the rendered
// byte content. Dest is stack-relative; the install/update writer
// joins it against the stack directory, creates nested parent
// directories per the confirmation rules, and parses Mode at the
// filesystem boundary — render carries the catalog's octal string
// forward unchanged so parse-failure surfacing stays with the write
// path, not render.
// Populated by [RenderLabels] when [Input.AdditionalFiles] is supplied.
type RenderedFile struct {
	// Dest is the stack-relative destination path (matches
	// internal/catalog.AdditionalFile.Dest; may contain nested
	// subdirectories the writer creates with mode 0o755 per
	Dest string

	// Mode is the POSIX file mode as an octal-with-leading-zero string
	// (e.g. "0644" for configs, "0755" for scripts). Mirrors
	// internal/catalog.AdditionalFile.Mode verbatim; the catalog
	// schema's ^0[0-7]{3}$ pattern constrains the format. The writer
	// parses it at the filesystem boundary — render carries it forward
	// unchanged so the render boundary stays free of parse policy.
	Mode string

	// Bytes is the rendered file content the writer drops at [Dest].
	Bytes []byte
}
